services:
  erp:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: erpautoreboque-tora

    network_mode: host

    env_file:
      - /etc/erp-autoreboque/erp.env

    environment:
      SERVER_ADDRESS: 127.0.0.1
      SERVER_PORT: 8080

    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"