spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erp_autoreboque_test
    username: erp_autoreboque_app
    password: ${TEST_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
jwt:
  secret: ${TEST_JWT_SECRET}
  expiration: 3600000

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false